/* Builds the GitHub Pages copy in ./docs: one self-contained index.html plus the images it asks for.
   A plain page has no extension APIs, so the two topSites calls are patched to no-ops - and every anchor
   is asserted, so moving one in the sources fails the build instead of shipping a page that throws. */

import { cp, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(fileURLToPath(import.meta.url));
const docs = path.join(root, "docs");
const read = (name) => readFile(path.join(root, name), "utf8");

const fail = (message) => {
  console.error(`build-site: ${message}`);
  process.exit(1);
};

const [html, css, lib, page, iconsJson, defaultsJson] = await Promise.all([
  read("new_tab.html"),
  read("new_tab.css"),
  read("lib.js"),
  read("new_tab.js"),
  read("icons.json"),
  read("defaults.json"),
]);

const STYLESHEET_LINK = /[ \t]*<link rel="stylesheet" href="new_tab\.css" \/>\n/;
const MODULE_SCRIPT = /[ \t]*<script type="module" src="new_tab\.js"><\/script>\n/;
const IMPORT_LINE = /^import \{[^}]*\} from "\.\/lib\.js";\n/m;
const LOADER_BLOCK = /const loadJson[\s\S]*?loadJson\("\.\/defaults\.json"\)\]\);\n/;
const API_LINE = "const api = globalThis.browser ?? globalThis.chrome;";
const TOPSITES_LINE = "    const browserSites = await api.topSites.get().catch(() => []);";

for (const [name, found] of [
  ["stylesheet link", STYLESHEET_LINK.test(html)],
  ["module script tag", MODULE_SCRIPT.test(html)],
  ["import line", IMPORT_LINE.test(page)],
  ["json loader block", LOADER_BLOCK.test(page)],
  ["api line", page.includes(API_LINE)],
  ["topSites call", page.includes(TOPSITES_LINE)],
]) {
  if (!found) fail(`${name} not found - the sources changed shape, update build-site.mjs`);
}

const pageSource = page
  .replace(IMPORT_LINE, "")
  .replace(LOADER_BLOCK, `const [icons, defaults] = [${iconsJson.trim()}, ${defaultsJson.trim()}];\n`)
  .replace(
    API_LINE,
    "// a plain page has no extension APIs: the stub makes every optional call a no-op\nconst api = globalThis.browser ?? globalThis.chrome ?? {};",
  )
  .replace(TOPSITES_LINE, "    const browserSites = api.topSites ? await api.topSites.get().catch(() => []) : [];")
  .trim();

const bundle = `${lib.replace(/^export /gm, "").trim()}\n\n${pageSource}`;
const inline = (text) => text.replace(/<\/script/gi, "<\\/script");

const out = html
  .replace(
    "<!doctype html>",
    "<!doctype html>\n<!-- generated by build-site.mjs from new_tab.html, new_tab.css, lib.js, new_tab.js," +
      " icons.json and defaults.json - edit those, then run `node build-site.mjs` -->",
  )
  .replace(
    STYLESHEET_LINK,
    `    <link rel="icon" href="./images/icon32.png" />\n    <style>\n${css.trim()}\n    </style>\n`,
  )
  .replace(MODULE_SCRIPT, `    <script>\n${inline(bundle)}\n    </script>\n`);

for (const [label, pattern] of [
  ["a stylesheet link", /rel="stylesheet"/],
  ["a module script", /type="module"/],
  ["an external script", /<script[^>]*\ssrc=/],
  ["an import", /\bimport\b/],
  ["an export", /\bexport\b/],
  ["a fetch call", /\bfetch\(/],
  ["a top level await", /^await /m],
]) {
  if (pattern.test(out)) fail(`the page still contains ${label}`);
}
if (!/<style>/.test(out)) fail("the page has no inline style block");

await rm(path.join(docs, "images"), { recursive: true, force: true });
await mkdir(path.join(docs, "images", "logos"), { recursive: true });
for (const file of await readdir(path.join(root, "images", "logos"))) {
  if (file.endsWith(".webp")) await cp(path.join(root, "images", "logos", file), path.join(docs, "images", "logos", file));
}
await cp(path.join(root, "images", "icon32.png"), path.join(docs, "images", "icon32.png"));
await writeFile(path.join(docs, "index.html"), out);

console.log(`build-site: wrote docs/index.html (${(Buffer.byteLength(out) / 1024).toFixed(1)} kB) and docs/images/`);
